ALTER TABLE users
    MODIFY COLUMN role enum('ADMIN','CITIZEN','COMPANY','EMPLOYEE','MANAGER') NOT NULL;

UPDATE users SET role = 'COMPANY' WHERE role = 'EMPLOYEE';

ALTER TABLE users
    MODIFY COLUMN role varchar(20) NOT NULL;